piro20_Ajax_Pirostagram/server/apps/comments/urls.py
from django.urls import path
from .views import *

app_name = 'comments'

urlpatterns = [
  path('list/', comment_list, name='list'),
  path('create/<int:post_pk>/', create, name='create'),
  path('delete/<int:post_pk>/<int:comment_pk>/', delete, name='delete'),
]

piro20_Ajax_Pirostagram/server/apps/posts/urls.py
from django.urls import path
from .views import *

#이부분도 참조할때 이용된다. posts:post_list 이런식으로
app_name = 'posts'

urlpatterns = [
    #name= 뒷부분은 참조할때 쓰이는 이름
    #파이썬에서 모듈 경로는 . 을  이용
    path('', post_list, name='post_list'),
    path('post_new/', post_new, name='post_new'),
    path('detail/<int:pk>/', detail, name='detail'),
    path('like_ajax/', like_ajax, name='like_ajax'),
]

piro20_Ajax_Pirostagram/server/config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    #장고 프로젝트의 루트 디렉토리 기준으로 경로 설정을 한다.
    path('admin/', admin.site.urls),
    path('', include('apps.posts.urls')),
    path('comments/', include('apps.comments.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

piro20_Ajax_Pirostagram/server/apps/comments/models.py
from django.db import models
from apps.posts.models import Post
# Create your models here.
class Comment(models.Model):
  comment = models.CharField('댓글', max_length=24)
  #각 댓글이 특정 포스트에 연결되어야 함
  post = models.ForeignKey(Post, null=True, on_delete=models.CASCADE)
  def __str__(self): # 파이썬의 특별한 메서드 중 하나로, 객체의 문자열 표현을 반환
    return self.comment

piro20_Ajax_Pirostagram/server/apps/posts/models.py
from django.db import models

# Create your models here
# 클래스는 붕어빵 틀,인스턴스는 붕어빵, 매서드는 붕어빵 기능
class Post(models.Model): #django 에 있는 models.Model을 상속 받음
    #필요한 필드 우선 생각
    #제목,내용,좋아요 우선 설정
    #시간 되면 사진도 직접 첨부할 수 있게  photo = models.ImageField('이미지', blank=True, upload_to='posts/%Y%m%d')
    #일단 지금은 post_list.html 에 같은 사진 넣어둠
    title = models.CharField(max_length=100) 
    content = models.TextField()
    like = models.IntegerField() #좋아요 수

piro20_Ajax_Pirostagram/server/apps/comments/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
  class Meta():
    model = Comment
    fields = ('__all__')

piro20_Ajax_Pirostagram/server/apps/posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

piro20_Ajax_Pirostagram/server/apps/comments/views.py
from django.shortcuts import render,redirect
from .forms import CommentForm
from .models import Comment
from apps.posts.models import Post
from django.shortcuts import get_object_or_404
from django.views.decorators.http import require_POST
# Create your views here.
def comment_list(request):
    comments =Comment.objects.all()
    ctx = {'comments': comments}
    return render(request, 'comments/comment_list.html', ctx)

def create(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('posts:detail', pk=post_pk)
    else:
        form = CommentForm()
    return render(request, 'comments/comment_create.html', {'form': form, 'post': post})
@require_POST
def delete(request, post_pk, comment_pk):
    comment = get_object_or_404(Comment, id=comment_pk)
    comment.delete()
    return redirect('posts:detail', pk=post_pk)

piro20_Ajax_Pirostagram/server/apps/posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post
from apps.comments.models import Comment
from .forms import PostForm

# Create your views here. 
def post_list(request): #request 는 http요청을 처리할때 사용되는 객체 , 객체란 클래스로 만들어진 붕어빵.
    #Post 에서 만든 title,content,like
    posts = Post.objects.all() #클래스인 Post 붕어빵 틀로 만든 객체 posts붕어빵
    ctx = {
        'posts': posts,
    }
    return render(request, 'posts/post_list.html', ctx) #객체와 함께 보여질 화면과 정보를 전달한다

#시간되면 글 생성도 
def post_new(request):
    #양식 채워서 제출할때
    if request.method == 'POST':
        form = PostForm(request.POST)
        #양식 바로 채워져있는지
        if form.is_valid():
            form.save()
            return redirect('posts:post_list') #여기서 apps name 이용 참조해야하니까
        else:
            ctx = {
                'form': form,
            }
            return render(request, 'posts/post_new.html', ctx)
    #게시글 만들기 페이지 방문할때
    elif request.method == 'GET':
        form = PostForm()
        ctx = {
            'form': form,
        }
        return render(request, 'posts/post_new.html', ctx)

def detail(request, pk):
    post = get_object_or_404(Post, id=pk)
    comments = Comment.objects.filter(post=post)
    return render(request, 'posts/post_detail.html', {'post': post, 'comments': comments})



def post_count(request):
    # 게시물 수 계산
    post_count = Post.objects.count()
    context = {
        'post_count': post_count,
    }
    return render(request, 'base.html', context)
#ajax 로 좋아요 수 늘리기
#생긴 의문점: 왜 이 부분만 json으로 바꿔주는거지 그냥 함수 만들어서 templates에 해당하는 html만들면 안되나
#해결: 전체 새로고침 X, 즉각적 결과 보여줌, 만약 ajax 이용안했으면 버튼 클릭할때마다 새로고침해야 바뀐 결과가 보여짐
    
import json #글자로 된 정보를 쓸 수 있는 형태로 바꿔줌
from django.http import JsonResponse #우리가 만든 정보를 웹페이지로 보내줄때 사용
from django.views.decorators.csrf import csrf_exempt #안전한지 확인?


@csrf_exempt # 위에 안전관련 잠깐 해제해주는 것 


#웹페이지와 서버간의 정보 교환은 json 이나 xml 데이터 형식으로 이루어지기에
def like_ajax(request):
    req=json.loads(request.body) # json 문자열을 python(우리가 동작 실행하는 함수를 만들었으니까)으로 변환하고
    post_id=req['id']

    post=Post.objects.get(id=post_id)
    post.like+=1
    post.save()

    return JsonResponse({'id':post_id,  'like': post.like}) #python을 json으로 바꿔 웹페이지에 전달한다.

piro20_Ajax_Pirostagram/server/templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <title>pirostagram</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{%static 'css/style.css'%}"> <!--manage.py 기준-->  
  <link rel="stylesheet" href="{%static 'css/reset.css'%}">  
  <script src="https://kit.fontawesome.com/5658349e28.js" crossorigin="anonymous"></script>
  {%block head%}


  {% endblock %}
</head>
<body>
  <main>
    <div class="container">
        <img src="{%static 'images/profile.png'%}" alt="프로필 사진" >

        <div class="profile-content-wrapper">
          <div class="profile-first-line">
              <div class="username" style="margin-left: 35px;">mnu_0722</div>
              <div class="buttons">
                  <button>프로필 편집</button>
                  <button>보관된 스토리 보기</button>
                  <button><i class="fa-solid fa-gears"></i></button>
              </div>
          </div>
          
          <div class="content">
              <span>게시물 {{post_count }}</span>
              <span>팔로워 420</span>
              <span>팔로잉 445</span>
          </div>
        </div>
        
    </div>

    {%block content%}
      
    
    {%endblock%}
  </main>


{% block extra %}
{% endblock %}
 
</body>
</html>

piro20_Ajax_Pirostagram/server/templates/comments/comment_create.html
{% extends 'base.html' %}
{%block head%}
  <title>comment_create</title>
{% endblock %}

{%block content%}
  <form
    action="{% url 'comments:create' post_pk=post.id   %}"
    method="post"
    enctype="multipart/form-data"
    class="create-comment"
  >
    {%csrf_token%} {{form.as_p}}
    <button class="btn btn-success" style="margin-left: 10px;">등록하기</button>
  </form>
{%endblock%}

piro20_Ajax_Pirostagram/server/templates/comments/comment_list.html
<!-- 사실 여기에 띄웠어야 했는데 detail.html에 댓글 목록 넣으려 하니까  -->

piro20_Ajax_Pirostagram/server/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="detail__container">
      <img src="{% static 'images/randomPic.png' %}" alt="기본이미지">
        <div class="comments-section">
            {% for comment in comments %}
              <div class="comment">
                <p>{{ comment.comment }}</p>
                <form action="{% url 'comments:delete' post.id comment.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">댓글 삭제하기</button>
                </form>
                  
              </div>
            {% empty %}
              <p style="margin-bottom: 10px;">댓글이 아직 없습니다.</p>
            {% endfor %}
            <button>
                <a href="{% url 'comments:create' post_pk=post.id %}" class="btn btn-primary" style="margin-top:10px;">댓글 추가하기</a>
            </button>
          </div>
        </div>
  </div>
{% endblock content %}

piro20_Ajax_Pirostagram/server/templates/posts/post_list.html
{% extends 'base.html' %}
{% load static %} 

{% block content %}
    <div class="main__container">
        {% for post in posts %} <!--posts는 아까 만든 붕어빵-->
            <div class="card post__container post-id-{{ post.id }}">
                <div class="card-body">
                    <div class="post__img">
                        <a href="{% url 'posts:detail' post.pk %}" >
                        <img src="{% static 'images/randomPic.png' %}" alt="기본이미지">
                        </a>
                    </div>
                    <!--의문점 객체 post 의 클래스Post 에 id 라는 필드를 만들지 않았는데 어떻게 이용 가능하지 ->장고에서 설정해준다함-->
                    <div class="btn btn-primary post__like" onclick="onClickLike({{post.id}}, event)">
                        <button>Like</button> {{ post.like }}
                    </div>
                    
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

{% block extra %}

<script>
     //객체를 생성한다
    const requestLike = new XMLHttpRequest();

    const onClickLike = (id, event) => {
        event.preventDefault();  // 페이지 새로고침 방지
        const url = "/like_ajax/";
         //서버에 요청을 보낸다
        requestLike.open("POST", url, true);
          //무슨방식으로?
        requestLike.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
        const data = new URLSearchParams({ id: id }).toString();
        requestLike.send(data);

        // 즉시 UI 업데이트
        const element = document.querySelector(`.post-id-${id} .post__like`);
        const currentLike = parseInt(element.textContent.split(" ")[1]) || 0;
        element.innerHTML = `<button>Like</button> ${currentLike + 1}`;
    };
  //서버 처리 함수 위에서 온 요청이 완료 되었는지 확인하는 함수
    requestLike.onreadystatechange = () => {
        if (requestLike.readyState == XMLHttpRequest.DONE) {
            if (requestLike.status < 400) {
                const { id, like } = JSON.parse(requestLike.response);
                const element = document.querySelector(`.post-id-${id} .post__like`);
                element.innerHTML = `<button>Like</button> ${like}`; // 서버에서 받은 좋아요 수로 업데이트
            }
        }
    };
</script>

{% endblock %} 