SWIDEA_SITE/server/apps/posts/urls.py
from django.urls import path
from .views import *

app_name='posts'
urlpatterns = [
    path('',main, name='main'),
    path('create/',create,name='create'),
    path('detail/<int:pk>/',detail, name='detail'),
    path('delete/<int:pk>/',delete,name='delete'),
    path('update/<int:pk>/',update,name='update'),
    path('toggle_star/<int:post_id>/', toggle_post_star, name='toggle_post_star'),
]

SWIDEA_SITE/server/apps/posts/models.py
from django.db import models
from apps.tools.models import Tool
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    title=models.CharField('제목' ,max_length=24)
    photo = models.ImageField(blank=True, upload_to='posts/%Y%m%d')
    content=models.CharField('내용',max_length=24)
    interest=models.IntegerField('관심도', default=0)

   
    #tool 외래키 참조
    tool= models.ForeignKey(Tool, on_delete=models.CASCADE)
def __str__(self):
    return self.title

class PostStar(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

SWIDEA_SITE/server/apps/posts/forms.py
from django import forms
from .models import Post
class PostForm(forms.ModelForm):
    class Meta():
        model=Post
        fields=('__all__')

SWIDEA_SITE/server/apps/posts/views.py
from django.shortcuts import render,redirect
from .forms import PostForm
from .models import Post,PostStar
from django.http import JsonResponse

# Create your views here.
def main(request):
   
    posts = Post.objects.all()  
    ctx={'posts': posts }
    return render(request,'posts/post_list.html',ctx)


def create(request):

    if request.method=='GET':
        form=PostForm()
        ctx={
            'form':form
        }
        return render(request,'posts/post_create.html' ,ctx)
    #post 일때 
    form=PostForm(request.POST, request.FILES)
    if form.is_valid():
        form.save()

    return redirect('posts:main')

def detail(request,pk):
     post=Post.objects.get(id=pk)
     tool=post.tool #정참조
     related_posts=tool.post_set.all() #역참조
     ctx={'post':post,'related_posts': related_posts}
     return render(request,'posts/post_detail.html',ctx)

def delete(request,pk):
    if request.method=='POST':
        #PK에 해당하는 POST개체 조회
        Post.objects.get(id=pk).delete()
    return redirect('posts:main')
    

def update(request,pk):
    post=Post.objects.get(id=pk)
    if request.method=='GET':    
        form=PostForm(instance=post)
        ctx={'form': form ,'pk':pk}
        return render(request,'posts/post_update.html',ctx)
    
    form=PostForm(request.POST,request.FILES, instance=post)

    if form.is_valid():
        form.save()
    return redirect('posts:detail',pk)

def toggle_post_star(request, post_id):
    post = Post.objects.get(id=post_id)
    post_star, created = PostStar.objects.get_or_create(user=request.user, post=post)

    if not created:
        post_star.delete() 

    return JsonResponse({'starred': created})

SWIDEA_SITE/server/apps/posts/templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{%static 'posts/css/style.css'%}"> 
  <link href="https://cdn.jsdelivr.net/npm/remixicon@4.0.0/fonts/remixicon.css" rel="stylesheet" /> 
  {%block head%}


  {% endblock %}
</head>
<body>
  <main>
   <!--nav-bar-->
   <a href="/">MY SW IDEA MANAGE</a>
   <a href="/create/">아이디어 등록</a>
   <a href="/">아이디어 관리</a>
   <a href="/tools/create/">개발툴 등록<a>
   <a href="/tools/list/">개발툴 관리</a>
    {%block content%}
      
    
    {%endblock%}
  </main>

  <!-- <script></script> -->
  <script>
    const minusBtn = document.getElementById('minus');
    const plusBtn = document.getElementById('plus');
    const countText = document.getElementById('cnt');

    // click 이벤트가 발생 -> 어떤 동작 실행
    // 여기서 말하는 동작 -> 함수
    // 이 함수는 countText 안에 있는 숫자를 가져와서, +1 -1

    minusBtn.addEventListener('click', () => {
      countText.innerText = Number(countText.innerText) - 1;
    })
    plusBtn.addEventListener('click', () => {
      countText.innerText = Number(countText.innerText) + 1;
    })
  </script>
  
</body>
</html>

SWIDEA_SITE/server/apps/posts/templates/posts/post_create.html
{% extends 'base.html' %}
{%block head%}
  <title>post_create</title>
{% endblock %}

{%block content%}
  <form
    action="{% url 'posts:create' %}"
    method="post"
    enctype="multipart/form-data"
  >
    {%csrf_token%} {{form.as_p}}
    <button>등록하기</button>
  </form>
{%endblock%}

SWIDEA_SITE/server/apps/posts/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  
  {% if post.photo.url != '' %}
    <img src="{{post.photo.url}}" alt="제품 이미지" />
  {% else %}
    <img src="{% static 'posts/image/no_img.png' %}" alt="대체 텍스트" />
  {% endif %}
  <h2>{{post.title}}</h2>
  <p>{{post.content}}</p>
  <p>관심도: {{post.interest}}</p>
  
  <a href="{% url 'tools:detail' post.tool.pk %}">개발툴: {{post.tool.name}}</a>
  <form action="{% url 'posts:delete' post.pk %}" method="POST">
    {%csrf_token%} 
    <button type="submit">삭제하기</button>
    <a href="{% url 'posts:main'  %}">목록</a>
    <a href="{% url 'posts:update' post.pk %}">수정하기</a>
   
  </form>
{% endblock content %}

SWIDEA_SITE/server/apps/posts/templates/posts/post_list.html
{% extends 'base.html' %}
{% load static %}

{%block head%}
  <title>my sw idea manage</title>
{%endblock%}

{%block content%}
  
  <div>
    {% for post in posts %}

    <div>
    <!--img-->
      {% if post.photo.url != null and post.photo.url != '' %}
        <img src="{{post.photo.url}}", alt="사진">
      {% else %}
     
      <img src="{% static 'posts/image/no_image.png'%}">
      {% endif %}
      <span class="star-button" data-post-id="{{ post.id }}">⭐</span>
  
    <!--내용-->
    <div>
      <a href="{% url 'posts:detail' post.pk%}">
        {{post.title}}
      </a>
      <p>예상 개발툴 :{{post.tool.name}}</p>
    </div>

    <!--관심도 버튼 -->

    <div id="main">
      <i class="ri-indeterminate-circle-line" id="minus"></i>
      <span id="cnt">{{ post.interest }}</span>
      <i class="ri-add-circle-line" id="plus"></i>
    </div>
    {% endfor %}
  </div>
{%endblock%}

SWIDEA_SITE/server/apps/posts/templates/posts/post_update.html
{% extends 'base.html' %}

{%block head %}
  <title>post_detail</title>
{%endblock%}

{%block content%}
  <form
    action="{% url 'posts:update' pk %}"
    method="post"
    enctype="multipart/form-data"
  >
    {%csrf_token%} {{form.as_p}}
    <button>수정 완료</button>
  </form>
{%endblock%}

SWIDEA_SITE/server/apps/posts/templates/tools/tool_create.html
{% extends 'base.html' %}
{%block head%}
  <title>tool_create</title>
{% endblock %}

{%block content%}
  <form
    action="{% url 'tools:create' %}"
    method="post"
  >
    {%csrf_token%} {{form.as_p}}
    <button>추가하기</button>
  </form>
{%endblock%}

SWIDEA_SITE/server/apps/posts/templates/tools/tool_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  
  <h2>{{tool.name}}</h2>
  <p>{{tool.kind}}</p>
  <p>관심도: {{tool.content}}</p>

  <a>만들 수 있는 sw목록</a>
  {% for post in posts %}
  <div>
    <h3>{{ post.title }}</a></h3>
  </div>
{% endfor %}
 
  <form action="{% url 'tools:delete' tool.pk %}" method="POST">
    {%csrf_token%} 
    <button type="submit" >삭제하기</button>
  </form>
  <a href="{% url 'tools:tool_list'  %}" >목록</a>
  <a href="{% url 'tools:update' tool.pk %}" >수정하기</a>
{% endblock content %}

SWIDEA_SITE/server/apps/posts/templates/tools/tool_list.html
{% extends 'base.html' %}
{% load static %}

{%block head%}
  <title>my sw idea manage</title>
{%endblock%}

{%block content%}

  <div>
    {% for tool in tools %}

    <div>
      <a href="{% url 'tools:detail' tool.pk %}">
        {{tool.name}}
      </a>  
      <p>종류: {{ tool.kind }}</p>
      <p>설명: {{ tool.content }}</p>
    </div>
    {% endfor %}
  </div>
{%endblock%}

SWIDEA_SITE/server/apps/posts/templates/tools/tool_update.html
{% extends 'base.html' %}
{%block head %}
  <title>tool_detail</title>
{%endblock%}

{%block content%}
  <form
    action="{% url 'tools:update' pk %}"
    method="post"
  >
    {%csrf_token%} {{form.as_p}}
    <button>수정 완료</button>
  </form>
  <hr>
  <form
    action="{% url 'tools:delete' pk %}"
    method="post"
  >
    {%csrf_token%}
    <button>삭제</button>
  </form>
{%endblock%}